drop htop on osx
It is no longer supported:

$ brew upgrade htop
==> Upgrading 1 outdated package, with result:
htop 2.0.2_1
htop: This formula either does not compile or function as expected on macOS
versions newer than Sierra due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.